linters:
  enable-all: true
  disable:
    - varnamelen
    - depguard
    - exhaustruct
    - mnd
    - wrapcheck
    - cyclop
    - errorlint
    - funlen
    - paralleltest
    - gochecknoglobals
    - testpackage

run:
  skip-dirs:
    - cmd/web

issues:
  exclude-files:
    - cmd/web/.*\\.go$
