name: golangci-lint
on:
  push:
  pull_request:

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Install templ
        shell: bash
        run: go install github.com/a-h/templ/cmd/templ@latest
      - name: Run templ generate
        shell: bash
        run: templ generate -path .

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
