name: golangci-lint
on:
  push:
  pull_request:

jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install templ
        shell: bash
        run: go install github.com/a-h/templ/cmd/templ@latest

      - name: Run templ generate
        shell: bash
        run: $(go env GOPATH)/bin/templ generate -path .

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          level: error
          go_version: 1.24
          reporter: github-pr-review
          golangci_lint_flags: "--config=.golangci.yml"
          filter_mode: nofilter
          github_token: ${{ secrets.GITHUB_TOKEN }}
